#pragma once

const char *var = R"DELIMETER(Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu placerat ipsum. Duis pharetra arcu in felis lacinia, a tincidunt tellus pretium. Vivamus rutrum dignissim tellus dignissim molestie. Cras sollicitudin placerat eros id aliquam. Nam et sem bibendum, accumsan massa et, hendrerit nibh. Nullam auctor a felis vel venenatis. Maecenas sed risus magna.

Fusce pretium dolor metus, a vulputate ante feugiat at. Nullam molestie lorem at dui maximus, quis congue arcu ultricies. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut nec lectus tortor. Praesent ut augue nibh. Suspendisse ac bibendum nunc, non finibus orci. Proin congue hendrerit lectus ut accumsan. Duis vel accumsan enim. Cras quam felis, congue eu nunc ac, dapibus luctus urna. Duis urna ex, condimentum non lectus vitae, vestibulum pretium lorem. Ut finibus nunc eu ex tempor rutrum.

Donec finibus massa placerat velit porttitor, vitae fringilla tortor imperdiet. Nulla pellentesque consequat justo. Suspendisse potenti. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque accumsan ornare lacus, vitae finibus erat. Ut pretium arcu ac ultrices scelerisque. Nunc eleifend elit nisl, quis interdum lectus facilisis ut. Nulla aliquet condimentum purus. In quis finibus turpis. Morbi in elit eget est sodales lacinia. Morbi pharetra lectus in lectus ultrices, sit amet condimentum mauris pulvinar. Nunc dapibus nulla eget accumsan aliquet. In urna arcu, pulvinar lacinia hendrerit vitae, cursus eget libero. Nunc sit amet nibh leo. Sed quis ipsum eros. Nulla nec consectetur neque.

Praesent elementum libero ac accumsan ornare. Cras mollis, eros id dictum varius, ligula felis dapibus orci, eget dapibus orci felis at purus. Nam congue mattis elit sed imperdiet. Vivamus pretium malesuada scelerisque. Donec ex orci, rutrum non ante eu, lobortis volutpat sapien. Duis ligula magna, pulvinar nec facilisis quis, sagittis vel justo. Duis in hendrerit lorem, sed feugiat ante. In consectetur arcu lorem, et euismod mauris imperdiet vitae.

Duis vitae viverra leo. Phasellus vitae urna a tellus rhoncus ultricies eget eget ipsum. Nunc aliquet id sem ut tristique. Maecenas ac sapien libero. Duis malesuada, sem vestibulum ullamcorper scelerisque, sem tellus tempor est, ac maximus erat risus vitae lectus. Pellentesque vitae risus metus. Morbi dapibus sodales est et pellentesque. Sed facilisis dolor sed sapien varius, eu commodo elit sollicitudin. Fusce sed vehicula arcu, fermentum commodo elit. Quisque eleifend at nibh et aliquam.

Phasellus sagittis nulla orci, eget imperdiet ipsum suscipit id. Fusce maximus ultrices sapien vel fringilla. In ut tincidunt lectus. Vivamus accumsan, quam non suscipit dictum, ipsum ex semper odio, pretium pellentesque libero orci in neque. Vestibulum orci erat, venenatis ac porta eu, auctor sit amet ex. Vivamus vestibulum sapien in augue bibendum pharetra. Donec a auctor dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent vel lacus aliquet augue lacinia laoreet quis non sapien. Fusce lacus velit, egestas id dictum in, tempor semper tellus.

Suspendisse quis augue a libero ullamcorper posuere eget quis felis. Maecenas convallis dolor ut erat vulputate cursus. Vivamus euismod imperdiet magna in pretium. In maximus metus in aliquet pretium. Curabitur bibendum semper leo, ut facilisis arcu imperdiet id. Proin libero ante, commodo ut efficitur vitae, interdum eu ex. Nullam quis accumsan felis, in elementum turpis. Quisque pretium nisi ac tempus faucibus. Sed tristique tincidunt turpis, varius posuere quam ornare eu. Proin ultricies commodo arcu, gravida varius ipsum. Cras non pretium ex, maximus luctus dolor. Fusce sed quam eget metus elementum tincidunt.

Phasellus maximus nisi at massa porta, eu commodo arcu aliquam. Aliquam sagittis tellus ac dolor venenatis, id ornare orci rutrum. Aliquam erat volutpat. Ut pharetra tellus nulla, at pulvinar velit scelerisque ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean tincidunt, justo in condimentum finibus, justo felis eleifend mauris, non ornare nulla velit vitae felis. Etiam luctus, est nec hendrerit elementum, libero ex tempor massa, id venenatis magna ante quis lacus. Donec nunc sem, tincidunt quis purus a, euismod sagittis metus. Phasellus egestas purus sit amet velit pellentesque, nec tincidunt orci mattis. Curabitur faucibus ante vitae metus faucibus, tincidunt lobortis dui pellentesque. Duis maximus ante nec purus interdum rhoncus.

Ut vestibulum eget dolor ut fermentum. Vestibulum elementum orci eu arcu egestas sollicitudin semper eu sem. Integer hendrerit sapien at justo porta, at consectetur justo imperdiet. Maecenas vitae risus non libero dapibus cursus a aliquet magna. Nulla facilisi. Ut dictum lacus sit amet neque sollicitudin, sed dictum sem consequat. Donec sagittis mauris nec turpis ultrices ultrices. Integer sagittis orci quis metus sagittis, ut tempor orci semper. Mauris quis sem vitae justo scelerisque aliquet id efficitur neque. Sed dictum aliquet mi, vitae faucibus lorem suscipit sed. Cras ut nisi sed nisi porttitor ultrices vel quis tellus. Nulla facilisi. Integer sed risus lacus. Fusce et mollis tortor. Proin dictum elit eget urna elementum facilisis.

Suspendisse vulputate, nulla nec commodo lacinia, ex nulla pulvinar dolor, vitae dictum tellus eros eget quam. Pellentesque nunc nisi, consectetur non leo id, fermentum tincidunt massa. Pellentesque tincidunt, sapien eget pretium volutpat, erat odio ornare ipsum, at ullamcorper erat mauris in eros. Donec non nibh leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque at consectetur justo, a imperdiet nunc. Sed iaculis elit ac magna tincidunt interdum. Curabitur eu eleifend neque, at malesuada nisl.

Vestibulum condimentum urna a felis dictum feugiat. Praesent maximus elit finibus posuere dictum. Phasellus nec velit in ligula commodo bibendum in et odio. Quisque commodo tincidunt ultrices. Curabitur vel cursus mauris. Quisque eleifend laoreet ipsum ac tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce id ornare diam, sed blandit risus. Aliquam eget augue pellentesque, sagittis nulla id, pulvinar velit. Curabitur sit amet nibh nec lectus aliquet consectetur. Quisque fringilla magna a metus sagittis, et molestie ante sodales. Nulla facilisi.

Pellentesque non nisi bibendum est viverra viverra in id tellus. In hac habitasse platea dictumst. Vivamus non velit sollicitudin, faucibus ipsum at, fermentum lacus. Vestibulum et ex malesuada, tristique tortor non, pulvinar nisl. Praesent tristique ipsum nec velit tristique, a maximus orci lacinia. Suspendisse vel nunc lectus. Aenean vitae magna ac diam tristique vulputate a a risus. Donec scelerisque tellus sit amet laoreet maximus. Aenean facilisis tortor id elit fringilla, non pharetra velit blandit. Vivamus tempus ipsum semper facilisis dignissim.

Donec fringilla sem ut porttitor dictum. Aliquam mollis semper augue, a sagittis nisl consequat in. Sed feugiat velit purus, at auctor orci varius sit amet. Suspendisse potenti. Aenean quis dui a risus interdum euismod eget sit amet neque. Fusce non erat pharetra, sodales eros ut, sagittis nibh. Sed id fringilla nunc. Duis lectus sapien, euismod in nunc non, sagittis tempus diam. Nulla et erat bibendum, vulputate neque nec, hendrerit nulla. Ut suscipit vitae neque sollicitudin sollicitudin. In hac habitasse platea dictumst. Donec ornare, felis a auctor mollis, est urna eleifend purus, sit amet volutpat dolor risus in tortor.

Nunc convallis interdum diam ac porttitor. Mauris ac enim pretium, venenatis odio in, faucibus ex. Donec non neque suscipit, tempus orci ut, consequat ante. Phasellus bibendum ligula ligula, id ultrices enim pulvinar nec. Vivamus interdum mauris sem. Aliquam nisi magna, vestibulum nec nunc nec, consectetur iaculis risus. Sed tincidunt ligula felis, nec aliquam magna posuere sit amet. Vestibulum vitae arcu finibus, scelerisque eros id, mollis eros. In tincidunt erat sit amet venenatis accumsan. Ut sed tortor nec sapien euismod sodales. In rhoncus mi dolor, at euismod risus lacinia in. Ut molestie malesuada porta. Aenean cursus, diam a sollicitudin egestas, diam lorem iaculis ex, vitae dictum ex libero ut velit. Duis varius ligula nunc, a tempor tortor cursus sed. Nunc vitae mi nec diam feugiat bibendum id sit amet quam. Nam consectetur leo erat, id porttitor quam vulputate sed.

Pellentesque viverra urna id arcu ultricies, sodales accumsan tellus feugiat. Aenean eget vehicula eros. Sed lorem nisi, blandit vitae metus iaculis, blandit consequat turpis. Sed non eros ac lectus consequat hendrerit. Curabitur a ultrices nisl. Nulla nec sem a elit rutrum cursus quis sed est. Vestibulum ultricies id metus eget pretium. Phasellus eu ex eu nisi efficitur facilisis sed varius enim. Donec cursus justo et placerat viverra. Sed condimentum efficitur consectetur. Suspendisse fermentum ultricies scelerisque. Aliquam viverra a nunc ac tempus. Maecenas pulvinar, sem at eleifend sagittis, dolor turpis feugiat purus, et accumsan orci nisi blandit odio. Integer justo erat, fringilla et scelerisque nec, finibus vel turpis.

Etiam vel vestibulum tellus. Quisque eros nisi, dictum sed pretium eget, scelerisque ac lacus. Donec porttitor sagittis dui. Aliquam maximus massa sed fermentum luctus. Nulla commodo laoreet neque, maximus sollicitudin massa vehicula et. In ultrices convallis efficitur. Sed eu commodo quam. Suspendisse sodales eros ut auctor fringilla. Vestibulum bibendum ipsum sit amet eros facilisis rhoncus. Fusce vitae lectus elementum, pretium tortor quis, porttitor lectus. Maecenas eu placerat turpis. Maecenas ullamcorper ac justo ut scelerisque. Donec suscipit, neque sed cursus maximus, magna ante porttitor purus, eu pellentesque elit ex at nisi. Donec molestie justo in consectetur blandit.

Donec euismod est in lacus pellentesque pulvinar. Sed a hendrerit sapien. Aenean fermentum ex nec diam pretium mattis. In eu commodo nunc, at pulvinar urna. Duis sit amet leo eu turpis tempor molestie vel sit amet magna. Aliquam scelerisque mauris nunc, eu mattis ipsum rhoncus eget. In at elementum arcu, vitae feugiat felis. Fusce euismod odio arcu, eleifend commodo lorem aliquet id. Donec dui risus, consectetur a suscipit a, pretium nec est.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris at nisi elementum, mollis libero a, dictum nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam turpis nulla, sollicitudin a fermentum sit amet, gravida ac metus. In hac habitasse platea dictumst. Pellentesque tristique, dolor vel lacinia interdum, lacus purus sodales quam, ut rhoncus orci erat sit amet sapien. Sed viverra dignissim nisl, at tincidunt magna eleifend et. Aenean vel ornare eros. Aenean nec nulla nibh. Donec maximus ex ut imperdiet sodales. Etiam feugiat dignissim sagittis. Vestibulum sed lacinia erat. Phasellus finibus, purus tempus tempor ullamcorper, velit est blandit velit, eget varius velit nulla vitae leo. Pellentesque cursus cursus sagittis. Mauris ac nisl eros. Ut risus mauris, vehicula ut est et, efficitur hendrerit ligula.

Quisque varius scelerisque purus eu posuere. Sed mattis tellus eu erat venenatis, sed consequat dui pretium. Etiam vel nisi nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec iaculis diam vitae lectus egestas, sed feugiat magna pellentesque. Etiam ornare odio eu magna viverra porta. In non leo ac felis fermentum posuere. Sed commodo nunc vel ultrices porta. Mauris efficitur ligula sed auctor luctus.

Vestibulum varius id odio et tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras dictum mauris nec augue interdum ultrices. Etiam ligula massa, eleifend at pretium quis, dignissim placerat enim. Nunc quis sollicitudin elit, pellentesque pretium sapien. Vestibulum bibendum rhoncus odio, vel tempor dolor vestibulum et. Nam tristique mollis mi, id vestibulum lorem venenatis eu. Donec elementum enim auctor, fringilla ante in, bibendum tortor. Cras elementum sodales ligula a semper. Proin euismod, lacus non elementum malesuada, ligula velit blandit erat, ut mollis metus est quis ipsum. Sed egestas ipsum eu libero pellentesque, ultrices consequat mi rutrum. Ut semper magna vel mi iaculis efficitur. Curabitur vestibulum nulla mi. Etiam semper quam tristique varius viverra. Cras placerat lorem in convallis efficitur. Etiam sollicitudin metus in porttitor commodo.

Donec at nunc ac turpis sollicitudin venenatis. Nam tincidunt, eros in pharetra pretium, enim massa tincidunt felis, et sodales lectus metus nec metus. Morbi pharetra quam erat. Nulla nec massa purus. Suspendisse sed semper nunc, nec placerat ante. Nam iaculis lorem ut viverra mollis. Nam vitae massa ipsum. Nunc et est nec diam iaculis tincidunt. Donec lorem sapien, laoreet nec est tempus, ornare cursus quam. Integer non nulla libero. Nam pharetra mauris porta arcu scelerisque, id mattis velit sagittis. Duis auctor aliquet metus, nec tempor est pulvinar nec.

Aliquam erat volutpat. Duis metus mi, ullamcorper sed nisi sit amet, viverra congue enim. Duis sollicitudin elementum metus ut commodo. Donec nunc orci, tempor non massa sed, interdum tincidunt risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. In pulvinar leo vitae lacinia imperdiet. Integer consequat consequat euismod. Proin laoreet at orci id eleifend. Vestibulum consequat tellus ante, non congue lorem dictum ac. Sed viverra tortor sed tellus sagittis faucibus. Nunc pulvinar sed odio ac sagittis. Aliquam quis egestas dui. Curabitur urna metus, rutrum ut dictum eget, faucibus vitae mi.

Integer enim nulla, egestas sit amet dolor eget, laoreet sollicitudin tellus. Aliquam erat volutpat. Praesent vel venenatis ante, vitae posuere augue. Maecenas vehicula libero nec consequat fringilla. Sed pellentesque dictum mi non hendrerit. In eros diam, pellentesque sed tellus ut, ornare scelerisque urna. Duis bibendum, purus ac cursus lacinia, orci risus blandit mauris, tristique tristique diam nisl ac sem. Ut congue erat leo, a posuere ex fringilla et. Cras quis lectus sit amet erat convallis bibendum. Quisque enim sem, varius vel felis a, rutrum pellentesque lectus. Sed auctor non ipsum sit amet tincidunt. Curabitur eu egestas augue, sit amet lacinia erat.

Donec tincidunt enim in urna mollis, efficitur mattis libero interdum. Suspendisse potenti. Donec eu rutrum leo. Vivamus a ligula iaculis, vulputate nibh in, feugiat eros. Quisque sit amet dui lobortis, sollicitudin nulla a, pellentesque quam. Etiam felis ex, pellentesque ut ante vitae, imperdiet imperdiet sapien. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque lacinia, tortor sit amet pretium semper, lorem orci commodo lorem, et hendrerit lectus eros eget nibh. Maecenas eu placerat felis. In accumsan ligula eu convallis rutrum. Etiam a rhoncus lorem.

Quisque accumsan nisi nec augue dictum, et mattis ipsum aliquet. Vestibulum in ornare felis. Vivamus id orci ut velit vestibulum pellentesque id eu ante. Fusce ac erat sed tortor ultrices vestibulum eget quis turpis. Sed consectetur ante ac scelerisque sagittis. Vivamus augue velit, ultrices non pulvinar a, efficitur ut mauris. Nunc eget hendrerit dui, eget tristique justo. Morbi condimentum ante dui. Cras interdum ante eu risus lobortis tincidunt. Mauris quis dapibus odio, fringilla venenatis nulla. Sed dapibus, nulla nec laoreet vehicula, mi odio varius felis, molestie commodo nisi leo in lectus. Aliquam vehicula tellus quis enim ornare, ut gravida mauris posuere.

Aenean elementum eleifend vestibulum. Nullam fringilla mi a lectus tempor consequat. Pellentesque cursus enim vel lacinia rhoncus. Mauris non euismod est. Sed lacinia eros leo, eget volutpat nunc sagittis id. Cras vitae metus metus. In faucibus risus at lorem consectetur, et aliquam justo hendrerit. Sed facilisis nibh eget bibendum vulputate. Cras in ultricies nulla, quis auctor tortor. Curabitur vitae facilisis est, a gravida sapien. Phasellus sagittis facilisis dui, vitae tempus diam consequat id. Integer orci ipsum, varius non sem eu, blandit congue erat.

Nulla faci)DELIMETER" R"DELIMETER(lisi. Integer ultrices, metus eu ultricies luctus, tortor nunc sagittis turpis, a egestas dui libero ut quam. In et porttitor nibh. Donec sollicitudin, mi ac facilisis condimentum, diam enim elementum nibh, ac dignissim libero turpis at sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce gravida, lectus a sollicitudin dictum, ante felis placerat eros, ac dictum ipsum augue in neque. Aenean id massa a libero euismod mollis.

Nam purus lacus, facilisis ac vehicula vel, euismod eu diam. Pellentesque quis bibendum nibh. Vivamus sit amet molestie mauris, tincidunt dapibus urna. In et magna nec quam pretium pulvinar. Vestibulum ligula augue, molestie ac justo sit amet, malesuada rhoncus odio. Curabitur finibus viverra justo quis pharetra. Aliquam eu est id velit hendrerit scelerisque. Sed vel eleifend turpis. Cras pulvinar lorem ut turpis rutrum dignissim. Donec non dolor quis orci aliquam aliquam a sed nibh. Sed dignissim cursus tincidunt.

Duis et molestie nisl, quis elementum nibh. Suspendisse potenti. Aliquam congue faucibus nibh non commodo. Nulla semper gravida urna quis sagittis. Nulla volutpat rutrum ultricies. Curabitur vel dui non libero convallis elementum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus sit amet elementum velit, sed lobortis dolor. Proin nec facilisis arcu. Cras justo lectus, aliquam sit amet imperdiet ullamcorper, convallis ac leo. Nunc finibus arcu nisi, in ultricies lorem sagittis sed. Integer at ornare mauris, at luctus nisi. Quisque sapien leo, porta sed ante vitae, rutrum pharetra libero.

Integer rutrum non massa ut luctus. Maecenas faucibus urna mauris, et malesuada quam luctus in. Ut interdum bibendum magna, sed gravida sem efficitur vitae. Duis imperdiet lacus in lorem pulvinar, ut varius magna imperdiet. Vestibulum elementum nisi eget finibus aliquam. Nam quis faucibus tellus. Aenean pretium nisi ut massa accumsan, sit amet malesuada erat tincidunt. Donec sit amet lacus euismod, feugiat neque vitae, convallis orci. Mauris tincidunt, nunc non molestie malesuada, risus urna mollis est, id tincidunt lacus lacus vel mauris. Nullam leo dui, pretium in velit eu, volutpat bibendum arcu. Praesent mattis, metus sit amet feugiat molestie, elit eros fringilla risus, ac aliquam erat justo ac quam. Cras ultrices, nunc non vulputate rutrum, nisl magna ullamcorper lectus, non aliquam nunc eros a sem. Curabitur odio nibh, convallis vel tempor eget, auctor et ex.

Aliquam id sapien nec diam ullamcorper tempus. Nam auctor libero leo, id auctor massa sollicitudin id. Vivamus non risus neque. In id feugiat mauris. Vivamus bibendum, nunc quis tincidunt mollis, eros tellus fermentum erat, non rutrum ante arcu ut mi. Mauris et velit leo. Duis tempor lectus a elit viverra, ac porttitor augue pulvinar. Sed sed consequat nibh, ut efficitur lorem. Pellentesque vehicula dapibus quam in placerat. Vivamus non augue id augue elementum viverra tincidunt non ipsum. Nullam aliquam nulla eget lectus facilisis sodales. Sed posuere placerat consectetur.

Maecenas id hendrerit elit. Aliquam porttitor enim nec mollis hendrerit. Phasellus venenatis eu mi et convallis. Morbi eget nisl lacinia, auctor leo non, suscipit dolor. In leo leo, tincidunt eu metus in, maximus posuere purus. Proin auctor enim quis risus maximus, ac ullamcorper est euismod. Integer in venenatis ligula. Cras a consequat arcu. Sed mattis nibh ut turpis commodo, et tristique neque vulputate.

Suspendisse feugiat, dui vel cursus porttitor, lectus arcu placerat risus, ac feugiat turpis justo in justo. In hac habitasse platea dictumst. Nullam pellentesque sed libero id posuere viverra.
)DELIMETER";
